Tampines.Web/Areas/Admin/Controllers/OurTownController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tampines.Web.Filters;
using Tampines.Web.Helpers;
using Tampines_CMS.Domain;
using Tampines_CMS.Persistence.Interface;

namespace Tampines.Web.Areas.Admin.Controllers
{
    [AuthenticationFilter]
    [DisableCache]
    [HandleError]
    public class OurTownController : Controller
    {
        #region Constructor And Private Members

        private IOurTownDao _ourTownDao;

        private IBannerDao _bannerDao;
        public OurTownController(IOurTownDao ourTownDao, IBannerDao bannerDao)
        {
            _ourTownDao = ourTownDao;
            _bannerDao = bannerDao;


        }

        #endregion
        // GET: Admin/OurTown
        public ActionResult Introduction()
        {
            if (TempData["data"] != null)
            {
                ViewBag.DataBaseStatus = "Changes Updated";
            }
            OurTown ourTown = _ourTownDao.GetOurTown();
            return View(ourTown);
        }
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Introduction(OurTown OT)
        {
            if (OT.Image1 != null && OT.Image1.ContentLength > 0)
            {
                OT.ImageExtension1 = Path.GetExtension(OT.Image1.FileName).Trim('.');
                OT.ImageName1 = Path.GetFileNameWithoutExtension(OT.Image1.FileName);
                OT.ImageGUID1 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID1 + "." + OT.ImageExtension1);
                OT.Image1.SaveAs(ThumbnailImagelocation);

            }
            if (OT.Image2 != null && OT.Image2.ContentLength > 0)
            {
                OT.ImageExtension2 = Path.GetExtension(OT.Image2.FileName).Trim('.');
                OT.ImageName2 = Path.GetFileNameWithoutExtension(OT.Image2.FileName);
                OT.ImageGUID2 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID2 + "." + OT.ImageExtension2);
                OT.Image2.SaveAs(ThumbnailImagelocation);

            }
            if (OT.Image3 != null && OT.Image3.ContentLength > 0)
            {
                OT.ImageExtension3 = Path.GetExtension(OT.Image3.FileName).Trim('.');
                OT.ImageName3 = Path.GetFileNameWithoutExtension(OT.Image3.FileName);
                OT.ImageGUID3 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID3 + "." + OT.ImageExtension3);
                OT.Image3.SaveAs(ThumbnailImagelocation);

            }
            OT.UserId = ((UserAccount)Session["UserAccount"]).GUID;
            OT.SystemIp = GetRemoteIp.GetIPAddress(HttpContext);
            Int64 Id = _ourTownDao.Save(OT);
            if (Id > 0)
            {
                TempData["data"] = "Success";
                return RedirectToAction("Introduction");
            }
            return View();
        }


        public ActionResult Preview()
        {
            return RedirectToAction("Introduction");
        }
        [HttpPost]
        [ValidateInput(false)]
        [ValidateAntiForgeryToken]
        public ActionResult Preview(OurTown OT)
        {
            if (OT.Image1 != null && OT.Image1.ContentLength > 0)
            {
                OT.ImageExtension1 = Path.GetExtension(OT.Image1.FileName).Trim('.');
                OT.ImageName1 = Path.GetFileNameWithoutExtension(OT.Image1.FileName);
                OT.ImageGUID1 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID1 + "." + OT.ImageExtension1);
                OT.Image1.SaveAs(ThumbnailImagelocation);

            }
            if (OT.Image2 != null && OT.Image2.ContentLength > 0)
            {
                OT.ImageExtension2 = Path.GetExtension(OT.Image2.FileName).Trim('.');
                OT.ImageName2 = Path.GetFileNameWithoutExtension(OT.Image2.FileName);
                OT.ImageGUID2 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID2 + "." + OT.ImageExtension2);
                OT.Image2.SaveAs(ThumbnailImagelocation);

            }
            if (OT.Image3 != null && OT.Image3.ContentLength > 0)
            {
                OT.ImageExtension3 = Path.GetExtension(OT.Image3.FileName).Trim('.');
                OT.ImageName3 = Path.GetFileNameWithoutExtension(OT.Image3.FileName);
                OT.ImageGUID3 = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Images/OurTown/" + OT.ImageGUID3 + "." + OT.ImageExtension3);
                OT.Image3.SaveAs(ThumbnailImagelocation);

            }
            OT.UserId = ((UserAccount)Session["UserAccount"]).GUID;
            OT.SystemIp = GetRemoteIp.GetIPAddress(HttpContext);
            ViewBannerModel viewBanner = _bannerDao.GetViewBanner();
            if (viewBanner != null && viewBanner.OurTownBanner != null && viewBanner.OurTownBanner.Count > 0)
                OT.OurTownBanner = viewBanner.OurTownBanner.Where(s => s.Page == "Introduction").FirstOrDefault();

            return View(OT);
        }

        public ActionResult TownMap()
        {
            if (TempData["data"] != null)
            {
                ViewBag.DataBaseStatus = "Changes Updated";
            }
            TownMapPDF town = _ourTownDao.GetTownMapPDF();
            return View(town);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult TownMap(TownMapPDF T)
        {
            if (T.PDFFile != null && T.PDFFile.ContentLength > 0)
            {
                T.PDFFileExtension = Path.GetExtension(T.PDFFile.FileName).Trim('.');
                T.PDFFileName = Path.GetFileNameWithoutExtension(T.PDFFile.FileName);
                T.PDFFileGUID = Guid.NewGuid().ToString("N");
                string ThumbnailImagelocation = Server.MapPath("~/Resources/Documents/OurTown/" + T.PDFFileGUID + "." + T.PDFFileExtension);
                T.PDFFile.SaveAs(ThumbnailImagelocation);

            }
            T.UserId = ((UserAccount)Session["UserAccount"]).GUID;
            T.SystemIp = GetRemoteIp.GetIPAddress(HttpContext);

            Int64 Id = _ourTownDao.SavePDF(T);
            if (Id > 0)
            {
                TempData["data"] = "Success";
                return RedirectToAction("TownMap");
            }
            return View();
        }


    }
}

Tampines.Web/Controllers/OurTownController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tampines_CMS.Domain;
using Tampines_CMS.Persistence.Interface;

namespace Tampines.Web.Controllers
{
    public class OurTownController : Controller
    {
        #region Constructor And Private Members

        private IOurTownDao _ourTownDao;

        private IBannerDao _bannerDao;
        public OurTownController(IOurTownDao ourTownDao, IBannerDao bannerDao)
        {
            _ourTownDao = ourTownDao;
            _bannerDao = bannerDao;


        }

        #endregion
        // GET: OurTown
        public ActionResult Introduction()
        {
            OurTown ourTown = _ourTownDao.GetOurTown();
            ViewBannerModel viewBanner = _bannerDao.GetViewBanner();
            if (viewBanner != null && viewBanner.OurTownBanner != null && viewBanner.OurTownBanner.Count > 0)
                ourTown.OurTownBanner = viewBanner.OurTownBanner.Where(s => s.Page == "Introduction").FirstOrDefault();
            return View(ourTown);
        }

        public ActionResult TownMap()
        {
            return View();
        }

        public ActionResult CyclingTown()
        {
            OurTownBanner banner = new OurTownBanner();
            ViewBannerModel viewBanner = _bannerDao.GetViewBanner();
            if (viewBanner != null && viewBanner.OurTownBanner != null && viewBanner.OurTownBanner.Count > 0)
            {
                 banner = viewBanner.OurTownBanner.Where(s => s.Page == "Cycling Town").FirstOrDefault();
            }
            return View(banner);
        }

        public ActionResult EcoTown()
        {
            OurTownBanner banner = new OurTownBanner();
            ViewBannerModel viewBanner = _bannerDao.GetViewBanner();
            if (viewBanner != null && viewBanner.OurTownBanner != null && viewBanner.OurTownBanner.Count > 0)
            {
                banner = viewBanner.OurTownBanner.Where(s => s.Page == "ECO Town").FirstOrDefault();
            }
            return View(banner);
        }
    }
}

Tampines.Web/Areas/Admin/Views/OurTown/Introduction.cshtml
@{
    ViewBag.Title = "Introduction";
    var appPath = Convert.ToString(ApplicationInstance.Application["ApplicationPath"]);
}
@model OurTown
<div class="maincontents">
    @using (Html.BeginForm("Introduction", "OurTown", FormMethod.Post, new { enctype = "multipart/form-data", id = "OurTownForm" }))
    {
        @Html.AntiForgeryToken()
        <h1>Our Town</h1>
        <h2>Introduction</h2>
        <div class="clear"></div>
        <div class="homepage">
            <table cellpadding="0" cellspacing="0" border="0" class="tblcreate">
                <tr>
                    <td class="fieldname">Image 01 <span class="importantNote">(600px by 400px)</span></td>
                    <td>
                        <div class="upload">
                            <input type="button" class="uploadBtn" value="Choose File">
                            <input type="file" name="Image1" id="Image1" data-imageWidth="" data-imageHeight="" />
                            <label>
                                @Html.TextBox("ImageFileNames1", (Model != null && !string.IsNullOrEmpty(Model.ImageName1) ? Model.ImageName1 + "." + Model.ImageExtension1.Trim('.') : ""), new { @type = "text", @placeholder = "No file chosen", @readonly = "true" })

                                @Html.HiddenFor(m => m.ImageGUID1)
                                @Html.HiddenFor(m => m.ImageExtension1)
                                @Html.HiddenFor(m => m.ImageName1)
                            </label>
                        </div>
                        @Html.ValidationMessage("Image1")
                        <div class="imgPreview"><img id="ImageFilePath1" src="@appPath/Resources/Images/OurTown/@Model.ImageGUID1.@Model.ImageExtension1"></div>
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">Image 01 Alt Tag</td>
                    <td>
                        @Html.TextBoxFor(m => m.ImageAltTag1, new { placeholder = "" })
                        @Html.ValidationMessageFor(m => m.ImageAltTag1)
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">Image 02 <span class="importantNote">(600px by 400px)</span></td>
                    <td>
                        <div class="upload">
                            <input type="button" class="uploadBtn" value="Choose File">
                            <input type="file" name="Image2" id="Image2" data-imageWidth="" data-imageHeight="" />
                            <label>
                                @Html.TextBox("ImageFileNames2", (Model != null && !string.IsNullOrEmpty(Model.ImageName2) ? Model.ImageName2 + "." + Model.ImageExtension2.Trim('.') : ""), new { @type = "text", @placeholder = "No file chosen", @readonly = "true" })

                                @Html.HiddenFor(m => m.ImageGUID2)
                                @Html.HiddenFor(m => m.ImageExtension2)
                                @Html.HiddenFor(m => m.ImageName2)
                            </label>
                        </div>
                        @Html.ValidationMessage("Image2")
                        <div class="imgPreview"><img id="ImageFilePath2" src="@appPath/Resources/Images/OurTown/@Model.ImageGUID2.@Model.ImageExtension2"></div>
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">Image 02 Alt Tag</td>
                    <td>
                        @Html.TextBoxFor(m => m.ImageAltTag3, new { placeholder = "" })
                        @Html.ValidationMessageFor(m => m.ImageAltTag3)
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">Image 03 <span class="importantNote">(600px by 400px)</span></td>
                    <td>
                        <div class="upload">
                            <input type="button" class="uploadBtn" value="Choose File">
                            <input type="file" name="Image3" id="Image3" data-imageWidth="" data-imageHeight="" />
                            <label>
                                @Html.TextBox("ImageFileNames3", (Model != null && !string.IsNullOrEmpty(Model.ImageName3) ? Model.ImageName3 + "." + Model.ImageExtension3.Trim('.') : ""), new { @type = "text", @placeholder = "No file chosen", @readonly = "true" })

                                @Html.HiddenFor(m => m.ImageGUID3)
                                @Html.HiddenFor(m => m.ImageExtension3)
                                @Html.HiddenFor(m => m.ImageName3)
                            </label>
                        </div>
                        @Html.ValidationMessage("Image3")
                        <div class="imgPreview"><img id="ImageFilePath3" src="@appPath/Resources/Images/OurTown/@Model.ImageGUID3.@Model.ImageExtension3"></div>
                    </td>
                </tr>
                <tr>
                    <td class="fieldname">Image 03 Alt Tag</td>
                    <td>
                        @Html.TextBoxFor(m => m.ImageAltTag3, new { placeholder = "" })
                        @Html.ValidationMessageFor(m => m.ImageAltTag3)

                    </td>
                </tr>
                <tr>
                    <td class="fieldname" colspan="2">Content</td>
                </tr>
                <tr>
                    <td colspan="2">
                        @Html.TextAreaFor(m => m.Content, new { @class = "ckeditor", @name = "Content", placeholder = "" })
                        @Html.ValidationMessageFor(m => m.Content)
                        @Html.HiddenFor(m => m.GUID)
                    </td>
                </tr>
            </table>
            <div class="padding10"></div>
            <div class="floatRight">
                <input type="button" id="previewBtn" class="submitBtn whiteBg" value="Preview">&nbsp;
                <input type="button" id="publishToLiveBtn" class="submitBtn whiteBg" value="Publish">
            </div>
            <div class="clear"></div>
        </div>
        <div class="clear padding10"></div>
    }
</div>
@if (ViewBag.DataBaseStatus != null)
{
    <div class="modal fade" id="ChangesUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content deletealert">
                <div class="modal-header">
                    <div class="title">Status</div>
                    <div class="close" data-dismiss="modal" aria-hidden="true">Close [X]</div>
                    <div class="clear"></div>
                </div>
                <div class="modal-body">
                    <div class="container" style="text-align:center;">


                        <div class="padding10"></div>

                        <div class="field"></div>
                        <div style="text-align: center;">
                            <p><strong>Changes Updated</strong></p>
                            <div class="padding10"></div>
                            &nbsp; &nbsp;
                            <a href="javascript:;" class="commonBtn close" data-dismiss="modal" aria-hidden="true">Ok</a>
                            <div class="clear padding10"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

@section scripts{


    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.validate.js"></script>
    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.validate.additional-methods.js"></script>
    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.alphanum.js"></script>
    <script src="@appPath/Contents/Admin/js/Custom/admin-ourtown-introduction.js"></script>

    <script src="@appPath/Contents/ckeditor/ckeditor.js"></script>

}

Tampines.Web/Areas/Admin/Views/OurTown/Preview.cshtml
@{
    ViewBag.Title = "Our Town | Tampines Town Council";
    Layout = "~/Areas/Admin/Views/Shared/_FrontEndLayout.cshtml";
    var appPath = Convert.ToString(ApplicationInstance.Application["ApplicationPath"]);
}
@section meta{
    <meta property="og:url" content="https://www.tampines.org.sg/our-town.html" />
    <meta property="og:title" content="Our Town | Tampines Town Council" />
    <meta property="og:description" content="" />
}
@model OurTown
<div class="mainContents">
    <div class="ourTown">
        <!--Page Banner-->
        <div class="pageBanner">
            @if (Model != null && Model.OurTownBanner != null)
            {
                <img src="@appPath/Resources/images/OurTownBanner/@Model.OurTownBanner.ImageGUID.@Model.OurTownBanner.ImageExtension" alt="">
            }
        </div>
        <!--Breadcrumb-->
        <div class="breadcrumb">
            <div class="container">
                <a href="javascript:void(0)">Home</a><span></span><a href="javascript:void(0)">Our Town</a><span></span>Introduction
            </div>
        </div>

        <!--Our Town (Introduction)-->
        <div class="pageContents introduction">
            <h1>Tampines Town Past &amp; Present</h1>

            <div class="imgContainer">
                <span><img src="@appPath/Resources/images/OurTown/@Model.ImageGUID1.@Model.ImageExtension1" alt="@Model.ImageAltTag1"></span>
                <span><img src="@appPath/Resources/images/OurTown/@Model.ImageGUID2.@Model.ImageExtension2" alt="@Model.ImageAltTag2"></span>
                <span><img src="@appPath/Resources/images/OurTown/@Model.ImageGUID3.@Model.ImageExtension3" alt="@Model.ImageAltTag3"></span>
            </div>
            <div class="padding10"></div>

            @Html.Raw(Model.Content)

            <div class="padding30"></div>
        </div>

    </div><!--End Our Town-->
</div><!-- End Main Contents -->

Tampines.Web/Areas/Admin/Views/OurTown/TownMap.cshtml
@{
    ViewBag.Title = "Introduction";
    var appPath = Convert.ToString(ApplicationInstance.Application["ApplicationPath"]);
}
@model TownMapPDF

<div class="maincontents">
    @using (Html.BeginForm("TownMap", "OurTown", FormMethod.Post, new { enctype = "multipart/form-data", id = "TownMapForm" }))
    {
        @Html.AntiForgeryToken()
        <h1>Our Town</h1>
        <h2>Town Map</h2>
        <div class="padding5"></div>
        <div class="formLayout">
            <table cellpadding="0" cellspacing="0" border="0" class="tblcreate">
                <tr>
                    <td class="fieldname">Upload PDF File</td>
                    <td>
                        <div class="upload">
                            <input type="button" class="uploadBtn" value="Choose File">
                            <input type="file" name="PDFFile" id="PDFFile" />
                            <label>
                                @Html.TextBox("PDFFileNames", (Model != null && !string.IsNullOrEmpty(Model.PDFFileName) ? Model.PDFFileName + "." + Model.PDFFileExtension.Trim('.') : ""), new { @type = "text", @placeholder = "No file chosen", @readonly = "true" })

                                @Html.HiddenFor(m => m.PDFFileGUID)
                                @Html.HiddenFor(m => m.PDFFileName)
                                @Html.HiddenFor(m => m.PDFFileExtension)
                                @Html.HiddenFor(m => m.GUID)
                            </label>
                        </div>
                        @Html.ValidationMessage("PDFFile")
                    </td>
                </tr>
            </table>
        </div>
        <div class="clear padding10"></div>
        <div class="floatRight">
            <input type="button" id="publishToLiveBtn" class="submitBtn whiteBg" value="Publish">
        </div>
        <div class="clear padding10"></div>
    }
</div>

@if (ViewBag.DataBaseStatus != null)
{
    <div class="modal fade" id="ChangesUpdate" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" data-backdrop="static">
        <div class="modal-dialog">
            <div class="modal-content deletealert">
                <div class="modal-header">
                    <div class="title">Status</div>
                    <div class="close" data-dismiss="modal" aria-hidden="true">Close [X]</div>
                    <div class="clear"></div>
                </div>
                <div class="modal-body">
                    <div class="container" style="text-align:center;">


                        <div class="padding10"></div>

                        <div class="field"></div>
                        <div style="text-align: center;">
                            <p><strong>Changes Updated</strong></p>
                            <div class="padding10"></div>
                            &nbsp; &nbsp;
                            <a href="javascript:;" class="commonBtn close" data-dismiss="modal" aria-hidden="true">Ok</a>
                            <div class="clear padding10"></div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}


@section scripts{


    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.validate.js"></script>
    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.validate.additional-methods.js"></script>
    <script type="text/javascript" src="@appPath/Contents/scripts/jqueryValidate/jquery.alphanum.js"></script>
    <script src="@appPath/Contents/Admin/js/Custom/admin-ourtown-townmap.js"></script>



}